### ISSUE TITLE
Project not even building for me

### ISSUE THREAD

**Issue by nishilshah17** [delannoyk/SoundcloudSDK#14]
After installing through CocoaPods and importing the framework, I'm getting a ton of errors.

When I open the project through .xcworkspace I'm getting all of these:
https://i.imgur.com/1lBkLux.png

When opening the project through .xcodeproj, I'm getting an error 'No such module 'Soundcloud'' even though I've installed. Do you know how to fix these errors by any chance?

**Comment by nishilshah17** [comment]
After reinstalling Xcode, it works.

**Comment by delannoyk** [comment]
This project is currently supporting Swift 2.2 only. The errors and warnings you had are probably there because you didn't have the last version of Xcode.
Anyway, glad to know it worked out for you!
