### ISSUE TITLE
Does this SDK support streaming/downloading/playing of songs?

### ISSUE THREAD

**Issue by larsblumberg** [delannoyk/SoundcloudSDK#15]
Hi! How does this SDK support streaming/downloading/playing of songs? By reading the readme file I couldn't figure it out. Should I feed `Track. streamURL` or `Track.downloadURL` to `AVPlayer` / `AVAudioPlayer`?

**Comment by delannoyk** [comment]
Hi,
This framework doesn't provide an audio player out of the box so yes, you have to use the `streamURL` or `downloadURL` to play the track using an `AVPlayer`. As far as I know, `AVAudioPlayer` doesn't support HTTP streams so it won't work using it.
If you're looking for an easy integration with an audio player, I can recommand [AudioPlayer](https://github.com/delannoyk/AudioPlayer).

**Comment by larsblumberg** [comment]
Thanks for your recommendation! Does your AudioPlayer support `streamURL`? Would you recommend streaming over downloading?

**Comment by delannoyk** [comment]
Yes it does, it's just a wrapper around AVPlayer so you don't have to deal with KVO, notifications etc.
Actually, you should use `streamURL` to stream the audio, and if your app has a download feature, you'd first have to check if `downloadURL` is not nil and then download it. But if you stay in the streaming part, use `streamURL` and you'll be fine.

**Comment by larsblumberg** [comment]
Thanks so much Kevin for your detailed answer!
