### ISSUE TITLE
Detect if a song is Soundcloud Go only

### ISSUE THREAD

**Issue by DragonMeistah** [delannoyk/SoundcloudSDK#16]
Hi again, for users without Soundcloud Go, they are unable to stream Soundcloud Go content in full. Could you possibly add a way to detect if a song is only available in full to Soundcloud Go users? Thanks!

**Comment by delannoyk** [comment]
Hi @DragonMeistah 

Soundcloud Go isn't yet available in my country. Do you have any idea if they added a way to know this (a new property in the JSON returned from the server)? I haven't found anything related to that on the API official documentation.

**Comment by delannoyk** [comment]
From what I understand [here](https://www.soundcloudcommunity.com/soundcloud/topics/soundcloud-go-api-access) it's not quite possible yet.

**Comment by willyptrain** [comment]
How do you import/implement this package into my iOS app?

**Comment by delannoyk** [comment]
@willyptrain with CocoaPods or Carthage, please follow the installation instructions.

@DragonMeistah I think that's not going to be available anytime soon... Closing this for now.
