### ISSUE TITLE
How to get a user's stream/timeline?

### ISSUE THREAD

**Issue by optikfluffel** [delannoyk/SoundcloudSDK#18]
Is there any example on how to get the currently authenticated user's stream/timeline?

**Comment by delannoyk** [comment]
1. Get a session (either from a new login or from the cached session):
   
   ``` swift
   Session.login(...) { response in
   }
   ```
   
    or 
   
   ``` swift
   let session = Soundcloud.session
   ```
2. Load activities:
   
   ``` swift
   session.activities { paginatedResponse in
   }
   ```

**Comment by delannoyk** [comment]
Code for this is [here](https://github.com/delannoyk/SoundcloudSDK/blob/master/sources/SoundcloudSDK/soundcloud/Soundcloud.swift#L253).
