### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by pablonnaoji** [delannoyk/SoundcloudSDK#19]
I havn't changed anything in my project yet, Im getting "SoundCloud has no member" for ClientID, ClientSecret and Redirect URI. 

I've tried cleaning the project and rebuilding but still having error. 

Is this happening to anyone else? delannoyk, has their been an API change? 

Thanks!

**Comment by delannoyk** [comment]
Hi @pablonnaoji 
There hasn't been any changes related to that, did it use to work?

**Comment by pablonnaoji** [comment]
Hey delannoyk! Thanks for getting back so quickly. 

   Yep, it was working perfectly fine, until a couple days ago. Im not sure what can be the problem because I did not change any code, I just opened it and it was throwing that "SoundCloud has no member" error. I was just curious to see if anyone else was having that problem because it seemed very odd, given that I hadn't changed any code at all. 

Thanks again for taking your time to look at this with me. 

-P

**Comment by pablonnaoji** [comment]
<img width="767" alt="screen shot 2016-07-05 at 11 53 08 pm" src="https://cloud.githubusercontent.com/assets/15187159/16609825/df2970c8-430b-11e6-9155-153f937890fe.png">

**Comment by delannoyk** [comment]
Hey!

I removed your screenshot since it contained private information for your app.
Anyway, back to your issue, this is weird... Silly questions but still worth asking, on the top of my head:
- did you `import Soundcloud`?
- Would you, by any chance have a class/struct of your own that is named `Soundcloud`?

**Comment by pablonnaoji** [comment]
Thanks delannoyk for the kind and tactful gesture.

 Yep I imported Soundcloud. Im pretty sure I dont have a class or Struct named "Soundcloud" either. But from my observation It was working fine one day, and the next day throwing that error. I'll double check on the naming of my classes and structs though.

**Comment by delannoyk** [comment]
Hi @pablonnaoji 
Found the issue?

**Comment by pablonnaoji** [comment]
Hey Kevin,

Sorry for the gap in communication.

I've been trying for sometime now to use the convert the json into a usable
format for a tableview. Do you have any pointers or sample code on how to
do this. Maybe even an explanation will help.

I wasn't sure if I needed to but I even downloaded this library on Github
to help in converting the json data returned as a Struct (Track) into a UI
object. https://github.com/matthewcheok/JSONCodable Do I need this library
to convert the data, or is it unnecessary?

Thanks for all your help!

-Paul
