### ISSUE TITLE
About Login function.

### ISSUE THREAD

**Issue by gi-ba** [delannoyk/SoundcloudSDK#21]
Hello Sir,
I try to implement the Login function into a button event. When i click that button, nothing happens. I tried to print the result of the response and it returns nil. In addition, I cannot get to the SoundCloud authorization page as well. Did I do anything wrong? Sorry I am just a newbie in iOS area. 
Looking forward to your reply.

Bao

**Comment by MchlG** [comment]
Could you please provide your code here?

**Comment by gi-ba** [comment]
Very thankyou for the fast reply. Here is my code. I just try to get to the authorization page and login.

> import UIKit
> import Soundcloud
> class ViewController: UIViewController {
> 
> ```
> override func viewDidLoad() {
>     super.viewDidLoad()
>     // Do any additional setup after loading the view, typically from a nib.
>     Soundcloud.clientIdentifier = "***********"
>     Soundcloud.clientSecret  = "************"
>     //Soundcloud.redirectURI = "YOUR_REDIRECT_URI"
> }
> 
> override func didReceiveMemoryWarning() {
>     super.didReceiveMemoryWarning()
>     // Dispose of any resources that can be recreated.
> }
> @IBAction func onLogout(sender: UIButton) {
>     let session = Soundcloud.session
>     session?.destroy()
> }
> 
> @IBAction func onLogin(sender: UIButton) {
>     Session.login(self) { (result: SimpleAPIResponse<Session>) in
>         print(result.response.result)
>     }
> 
> }
> ```
> 
> }

**Comment by gi-ba** [comment]
Hi,
I have just fixed the problem by setting the redirectURI : "http://google.com". Now I can login. But I got the problem which is: "canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "This app is not allowed to query for scheme org-appextension-feature-password-management" ". Never seen that before.
Bao

**Comment by delannoyk** [comment]
Hi,

Sorry for delayed answer! So to answer both of your issues:

`redirectURI` shouldn't be google.com, but the redirect URI you set on Soundcloud when creating your app.

> canOpenURL: failed for URL: "org-appextension-feature-password-management://

This is related to OnePassword integration. If you want to be able to use OnePassword when logging in - and remove this warning - you can add this to your Info.plist:

```
<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>org-appextension-feature-password-management</string>
    </array>
```
