### ISSUE TITLE
SoundcloudWebViewController buttonOnePasswordPressed error

### ISSUE THREAD

**Issue by kseniya-hydric** [delannoyk/SoundcloudSDK#23]
SoundcloudWebViewController.swift line 76 is giving an error "Nill is not compatible with expected argument type 'OnePasswordSuccessCompletionBlock'". This breaks the build.

**Comment by delannoyk** [comment]
Hm, is there any chance you performed a `pod update`? If so, OnePasswordExtension might have been updated to a new version which isn't supported yet. I'll update the pod on the podfile a bit later today to fix that! Thanks for reporting.

**Comment by kseniya-hydric** [comment]
Yes I did! Thanks, will keep an eye out for the update :)
