### ISSUE TITLE
Add searching of Soundcloud

### ISSUE THREAD

**Issue by chrisetheridge** [delannoyk/SoundcloudSDK#3]
It would be great to be able to search Soundcloud via track name / artist / album etc. and get back a Track identifier.

**Comment by delannoyk** [comment]
Hi!
Yep I agree, definitely going to be on my todo :)

I looked up at SC API and indeed we can query for searching a string. In the implementation you should get a full Track though. I'll add this next week.

**Comment by chrisetheridge** [comment]
I can maybe hack something together today? I am no expert at Swift but I do know the Soundcloud API pretty well. You could just do a POST to the API with the search query, and parse the JSON request to get the identifier out? The identifier can then be passed to the Track.track(indentifier) method.

**Comment by delannoyk** [comment]
Done in 0.3.0.
Have fun :-)

**Comment by chrisetheridge** [comment]
You are awesome! Thanks a lot!
