### ISSUE TITLE
Crash when logging in on Swift 3 version

### ISSUE THREAD

**Issue by kseniya-hydric** [delannoyk/SoundcloudSDK#30]
Getting a crash on line 148 in Request.swift straight after login to Soundcloud. Looks like an infinite loop originated from 'token' method completion.

**Comment by trevlevieux** [comment]
Same here

**Comment by delannoyk** [comment]
On it

**Comment by delannoyk** [comment]
Solved on master. Thanks for reporting as I have very little time right now (moving at the opposite side of the globe :)).
