### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by ziiw** [delannoyk/SoundcloudSDK#32]
Hey !

I'm trying to use your project im my swift 3 app, but it seems that pod install always go to v0.9

```
...
Using Soundcloud (0.9)
...
```

```
platform :ios, '10.0'
use_frameworks!
...
pod 'Soundcloud'
```

Do I miss something ? :) 

Regards,

**Comment by ziiw** [comment]
Oops sorry. Duplicate of #25

**Comment by delannoyk** [comment]
Can you use `pod update` to see if that links to 1.0.0?

**Comment by ziiw** [comment]
I've tried with `pod 'Soundcloud', :git => 'https://github.com/delannoyk/SoundcloudSDK', :branch => 'master'` and it work like a charm :)
