### ISSUE TITLE
[Users] - Add search

### ISSUE THREAD

**Issue by ziiw** [delannoyk/SoundcloudSDK#33]
Hey !

I've been using your SDK for several weeks now, such a great work :)

Today I need to create a user search but it's not implemented yet. I think it will be great and useful ^^

```
let query = "http://api.soundcloud.com/users.json?q=" + escapedString! + "&consumer_key=" + Soundcloud.clientIdentifier! + "&limit=5&offset=0"
```

That's the way we can query for users. Not explain at all on Soundcloud docs... If I have time I will PR, but right now I can't do it.

**Comment by delannoyk** [comment]
Working on it.

**Comment by delannoyk** [comment]
There you go! `1.0.1` has been released!

**Comment by ziiw** [comment]
All right ! That was fast haha. Thx i'll check it out right now !
