### ISSUE TITLE
Cancelling requests

### ISSUE THREAD

**Issue by intonarumori** [delannoyk/SoundcloudSDK#34]
Is there a way to cancel pending requests?
The model extensions could return the created request objects for this specific purpose.

**Comment by delannoyk** [comment]
There is currently none.
I think they could but one of the issues with the current Request model is that I would have to make a lot of internal types public + probably remove the generic part so that it's easier to use outside the module.

**Comment by intonarumori** [comment]
Thanks for the response.
What you could do is to return a Protocol (ex. CancelableRequest) that only exposes the `cancel` method. This way you wouldn't have the headache of changing types and touching the generics.

Did you find any publicly available examples that improved on this type of Request handling design?

**Comment by delannoyk** [comment]
Pushed to master, going to release a new pod version later today.
