### ISSUE TITLE
Redirect_URI issue

### ISSUE THREAD

**Issue by asterhouse** [delannoyk/SoundcloudSDK#4]
"invalid client: The configured redirect_uri of the client application is invalid" I get this whenever I use Session.login(self, completion: { result in
        })

I'm not sure what is causing this problem because my clientID, clientSecret, and redirectURI all match that in my developer account with soundcloud. Any help on resolving this problem?

**Comment by delannoyk** [comment]
Hi,
Are you sure you use the same (including scheme, path, ...)? If so, could you tell me what it is so that I create a fake app with the same setting?
Thanks!

**Comment by asterhouse** [comment]
I'm not sure what you mean by scheme and path. Can you give an example of what that should look like?

**Comment by asterhouse** [comment]
My app is called chordinate. and the Redirect_URI I put in my info.plist is chordinate://

**Comment by asterhouse** [comment]
I realized I needed to have a real URL for the redirect. I'm not sure what the use of it is, but I put in the index page of my website and now it works.

**Comment by delannoyk** [comment]
Mh. This is my configuration for my app on SC:
![screen shot 2015-11-23 at 09 09 00](https://cloud.githubusercontent.com/assets/1777691/11332027/108f85cc-91c2-11e5-9b90-d250ff702bde.png)

So in my app: `Soundcloud.redirectURI = "bemusic://soundcloud"` and it works :/

**Comment by asterhouse** [comment]
I wasn't able to use a URI like that but when I put a real URL in it's place and matched that to my soundcloud dev account, it worked perfectly. Thanks!

**Comment by ziiw** [comment]
Hey !

I've got some trouble with my redirect_uri too. I'm surely missing something, but I don't understand why my logging is prompting a white screen.

I've done my configuration like:

```
// Soundcloud
Soundcloud.clientIdentifier = "Client"
Soundcloud.clientSecret  = "Secret"
Soundcloud.redirectURI = "host:port/path"
```

It's configured as well in my Soundcloud app configuration. Do you know why I'm not getting the login form from Soundcloud and instead getting a white page ?
