### ISSUE TITLE
[OAuth] - token and me/ soundcloud

### ISSUE THREAD

**Issue by ziiw** [delannoyk/SoundcloudSDK#43]
Hey !

I'm working with your repo since a while as you know.

Well I'm having trouble getting tracks of a soundcloud profile. Seems like you donc use/store the oauth-token, when logging, or not using it to make some calls, is that right ?

I figure it out, that for some reasons, some profile have to be connected on their own Soundcloud account to get the music of their profile. Ex: I want the tracks of DJ Snake, I will not be able to get them by doing this:
```
https://api.soundcloud.com/users/670089/tracks?client_id=client_id
```
or 
```
// Logged in with a random soundcloud account
// Trying to get music from DJ Snake profile

User.user(identifier: 670089, completion: (resp){
    if let user = resp.response.result{
        user.tracks(completion: (res){
             print(res.response.result)    // []
        })
    }
})
```

 Therefore if I am the owner of this account I can log me in and then with the oauth-token I can grab the tracks be doing: 
```https://api.soundcloud.com/me/tracks?limit=100&offset=0&format=json&oauth_token=token```

So here are two questions:
* I can't figure it ou if you're using token to make special calls ?
* How to build this query with your lib `https://api.soundcloud.com/me/tracks?limit=100&offset=0&format=json&oauth_token=token`

Thanks for your informations ;)

**Comment by delannoyk** [comment]
Hey Adrien!

Quick answers:
> I can't figure it ou if you're using token to make special calls ?

I am currently using the oauth token for private calls only - such as following a member or favouriting a track.

> How to build this query with your lib https://api.soundcloud.com/me/tracks?limit=100&offset=0&format=json&oauth_token=token

The answer is that you currently can't :/ 

I will have to check the documentation to find out what a user can set to be private or public. My guess based on your comment is `tracks` and `playlists`.

Keep you posted soon on this!

**Comment by ziiw** [comment]
Ok great thanks for your answer :)

Using curl this request: `https://api.soundcloud.com/me/tracks?limit=100&offset=0&format=json&oauth_token=token` works like a charm so I guess that you can do it from iOS.

If you think that's not possible, can you release the auth_token as a public var ? In that way I will make my own call ?

Cheers !

**Comment by mparrish91** [comment]
Is this to retrieve a current users Reposts? Any luck

**Comment by delannoyk** [comment]
@mparrish91 You should be able to retrieve logged user's reposts by using `Session.activities(completion: @escaping (PaginatedAPIResponse<Activity>) -> Void)` but this isn't part of this issue.

@ziiw The 1.1.0 version now sends the `oauth_token` along with other parameters when it's available (and btw, the access token is already public 😊).
