### ISSUE TITLE
About if it's necessary to ease up things to play a file

### ISSUE THREAD

**Issue by sparkxxf** [delannoyk/SoundcloudSDK#5]
I think  integrate an audio player/a dependency is cost more time and not agile. 

In my opinion, the best way is  a beautiful Calling Method for anyone who want to integrate any audio core player.

**Comment by delannoyk** [comment]
When you say

> a beautiful Calling Method

what do you mean exactly?

**Comment by sparkxxf** [comment]
I mean let people change to any audio player easy and simple is better than
built in a good audio player.
