### ISSUE TITLE
Create Playlist

### ISSUE THREAD

**Issue by DragonMeistah** [delannoyk/SoundcloudSDK#8]
Hey this is awesome, thanks for sharing! It would be awesome if we could create/manipulate playlists

**Comment by delannoyk** [comment]
Yeah I agree that would be a great feature.
Unfortunately, I don't see any API to create a Playlist and it seems there's one for editing.
I'll check out what I can do from there!

**Comment by MusicSplitterGit** [comment]
Awesome thank you for this!

**Comment by DragonMeistah** [comment]
Hey Kevin any word on this? I am just wondering because If you do not think you can add it to your SDK, then I will simply work something out with my own database that shares the necessary data to be able to add/edit playlists :)

**Comment by delannoyk** [comment]
Hi @DragonMeistah
Sorry about this, haven't had a lot of time lately. I should have some time around next week to check it out.

**Comment by DragonMeistah** [comment]
Now worries! Thanks for the response. I love the SDK that you have provided. I hope the playlist feature is do-able!

**Comment by DragonMeistah** [comment]
Any luck?

**Comment by MusicSplitterGit** [comment]
If not, is there a way to load all the favorited tracks for any user given a user identifier?

**Comment by DragonMeistah** [comment]
If this is not possible, then is there anyway to --> get all tracks favorited by any user, given that user's identifier?

**Comment by delannoyk** [comment]
Ok so, as I already said, the API doesn't let _create_ new playlists but the edition seems possible although not entirely sure.
I'm currently having priorities on another project of mine but be sure that I will keep you guys posted when I'm working on this. Also, I do accept Pull Requests and they are more than welcomed, if my timing doesn't fit yours.

> If this is not possible, then is there anyway to --> get all tracks favorited by any user, given that user's identifier?

You wouldd first have to fetch the user's profile, with the current request architecture, but yes, it's possible.

``` swift
User.user(identifier) { simpleResponse in
    simpleResponse.response.result!.favorites { paginatedResponse in .... }
}
```

**Comment by DragonMeistah** [comment]
Ok, thank you!

**Comment by delannoyk** [comment]
I know it's late, but it might be coming tomorrow night! ('Cause WWDC today :P)

Details for API call:

## Playlist creation

**POST**: https://api.soundcloud.com/playlists/
**Payload**:

```
playlist[title]={PlaylistName}&playlist[sharing]={TypeOfSharing (private|public)}&playlist[_resource_id]=undefined&playlist[_resource_type]=playlist
```

=> Get the identifier of the playlist

## Add a Track to the playlist

**PUT**: https://api.soundcloud.com/playlists/{identifier}
**Payload**: 

```
{
    "playlist": {
        "tracks": [{
            "id": {track_identifier}
        }, ....]
    }
}
```

for every track in the playlist, the tracks should contains and send it to the API (although a Track might already be in the playlist).

**Comment by delannoyk** [comment]
Annnnnnnnnd, done! Available on master, no release yet (still have to document the feature).

### Usage:

``` swift
Playlist.createWithName("PLAYLIST_NAME", sharingAccess: (.Public | .Private)) { response in }

let playlist: Playlist
playlist.addTrack/addTracks([identifiers]) { response in }
playlist.removeTrack/removeTracks([identifiers]) { response in }
```

**Comment by DragonMeistah** [comment]
most excellent thank you!!!
